WareblocksWebUI/Models/Idea/IdeaModel.cs
namespace WareblocksWebUI.Models.Idea
{
    public class IdeaModel
    {
        public ShortGuid Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PositiveVotes { get; set; }
        public int NegativeVotes { get; set; }
        public string ProjectId { get; set; }
    }
}

WareblocksWebUI/Models/Idea/IdeaViewModel.cs
using System.Collections.Generic;
using WareblocksWebUI.Models.Comment;

namespace WareblocksWebUI.Models.Idea
{
    public class IdeaViewModel
    {
        public IEnumerable<IdeaModel> Ideas { get; set; }
        public string ProjectId { get; set; }
    }
}

WareblocksWebUI/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Application.Core;
using AutoMapper;
using DomainDTO.Implementations;
using Microsoft.AspNet.Identity;
using WareblocksWebUI.Models;
using WareblocksWebUI.Models.Comment;

namespace WareblocksWebUI.Controllers
{
    public class CommentController : Controller
    {
        public ApplicationEntry Application { get; set; }

        public CommentController()
            : this(new ApplicationEntry())
        {
        }

        private CommentController(ApplicationEntry applicationEntry)
        {
            Application = applicationEntry;
        }

        public ActionResult GetCommentsForProject(string projectId)
        {
            var projectGuid = (ShortGuid)projectId;

            var comments = Application.GetCommentsForProject(new ProjectDto {Key = projectGuid});

            return PartialView("Comments", new CommentViewModel {Comments = Mapper.Map<IEnumerable<CommentDto>, IEnumerable<CommentModel>>(comments)});
        }

        public ActionResult GetCommentsForFeature(string featureId)
        {
            var featureGuid = (ShortGuid)featureId;

            var comments = Application.GetCommentsForFeature(new FeatureDto { Key = featureGuid });

            return PartialView("Comments", new CommentViewModel { Comments = Mapper.Map<IEnumerable<CommentDto>, IEnumerable<CommentModel>>(comments) });
        }

        public ActionResult GetCommentsForIdea(string ideaId)
        {
            var ideaGuid = (ShortGuid)ideaId;

            var comments = Application.GetCommentsForIdea(new IdeaDto { Key = ideaGuid });

            return PartialView("Comments", new CommentViewModel { Comments = Mapper.Map<IEnumerable<CommentDto>, IEnumerable<CommentModel>>(comments) });
        }

        [HttpPost]
        public ActionResult AddComment(CommentModel createModel)
        {
            var createDto = Mapper.Map<CommentModel, CommentDto>(createModel);

            createDto.User = new UserDto { Id = new Guid(User.Identity.GetUserId()) };

            if (createModel.ProjectId != null)
            {
                createDto.Project = new ProjectDto {Key = (ShortGuid) createModel.ProjectId};
                Application.AddCommentToProject(createDto);
                return GetCommentsForProject(createModel.ProjectId);
            }   

            if (createModel.FeatureId != null)
            {
                createDto.Feature = new FeatureDto { Key = (ShortGuid)createModel.FeatureId };
                Application.AddCommentToFeature(createDto);
                return GetCommentsForFeature(createModel.FeatureId);
            }

            if (createModel.IdeaId != null)
            {
                createDto.Idea = new IdeaDto { Key = (ShortGuid)createModel.IdeaId };
                Application.AddCommentToIdea(createDto);
                return GetCommentsForIdea(createModel.IdeaId);
            }

            return null;
        }
    }
}

WareblocksWebUI/Controllers/FeatureController.cs
using Application.Core;
using AutoMapper;
using DomainDTO.Implementations;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WareblocksWebUI.Models;
using WareblocksWebUI.Models.Comment;
using WareblocksWebUI.Models.Feature;

namespace WareblocksWebUI.Controllers
{
    [Authorize]
    public class FeatureController : Controller
    {
        public ApplicationEntry Application { get; set; }

        public FeatureController()
            : this(new ApplicationEntry())
        {
        }

        private FeatureController(ApplicationEntry applicationEntry)
        {
            Application = applicationEntry;
        }

        // GET: Feature
        public ActionResult Index(string featureId)
        {
            var projectFeatureDto = new FeatureDto { Key = (ShortGuid)featureId };
            var result = Application.Get(projectFeatureDto);
            
            var projectFeatureModel = Mapper.Map<FeatureDto, FeatureModel>(result);
            
            return PartialView(projectFeatureModel);
        }

        public ActionResult Create(string projectId)
        {
            return PartialView(new FeatureModel { ProjectId = ((ShortGuid)projectId) });
        }

        [HttpPost]
        public ActionResult Create(FeatureModel createModel)
        {
            var projectFeatureDto = Mapper.Map<FeatureModel, FeatureDto>(createModel);
            projectFeatureDto.Project = new ProjectDto { Key = (ShortGuid)createModel.ProjectId };

            Application.Insert(projectFeatureDto);

            return RedirectToAction("Index", "Project", new { id = (ShortGuid)createModel.ProjectId });
        }

        [HttpGet]
        public ActionResult GetFeaturePopup(string featureId)
        {
            var projectFeatureDto = new FeatureDto { Key = (ShortGuid)featureId };
            var result = Application.Get(projectFeatureDto);
            return View(result);
        }

        public ActionResult FeaturesByProject(string projectId)
        {
            var result = Application.GetAllFeaturesFromProject(new ProjectDto { Key = (ShortGuid)projectId });
            var allFeaturesFromProject = Mapper.Map<IEnumerable<FeatureDto>, IEnumerable<FeatureModel>>(result);
            var viewModel = new FeatureViewModel { Features = allFeaturesFromProject, ProjectId = projectId };
            return PartialView(viewModel);
        }

        public ActionResult GetPaymentPopup()
        {
            return PartialView("Payment", new PaymentModel());
        }

        public ActionResult GetPaymentResult()
        {
            return PartialView("PaymentResult");
        }

        [HttpPost]
        public ActionResult Vote(string featureId, bool isLike)
        {
            var featureGuid = (ShortGuid)featureId;
            var userId = Guid.Parse(User.Identity.GetUserId());
            Application.VoteFeature(featureGuid, userId, isLike);
            return null;
        }
    }
}

WareblocksWebUI/Controllers/IdeaController.cs
using Application.Core;
using AutoMapper;
using DomainDTO.Implementations;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WareblocksWebUI.Models;
using WareblocksWebUI.Models.Comment;
using WareblocksWebUI.Models.Idea;

namespace WareblocksWebUI.Controllers
{
    [Authorize]
    public class IdeaController : Controller
    {
        public ApplicationEntry Application { get; set; }

        public IdeaController()
            : this(new ApplicationEntry())
        {
        }

        private IdeaController(ApplicationEntry applicationEntry)
        {
            Application = applicationEntry;
        }

        public ActionResult Index(string ideaId)
        {
            var ideaDto = new IdeaDto() { Key = (ShortGuid)ideaId };
            
            var result = Application.Get(ideaDto);
            var projectFeatureModel = Mapper.Map<IdeaModel>(result);

            return View(projectFeatureModel);
        }

        [HttpPost]
        public ActionResult Create(IdeaModel createModel)
        {
            var toCreate = Mapper.Map<IdeaDto>(createModel);
            toCreate.Project = new ProjectDto() { Key = (ShortGuid)createModel.ProjectId };

            Application.Insert(toCreate);

            return RedirectToAction("Index", "Project", new { id = (ShortGuid)createModel.ProjectId });
        }

        public ActionResult Create(string projectId)
        {
            return PartialView(new IdeaModel { ProjectId = ((ShortGuid)projectId) });
        }

        public ActionResult IdeasByProject(string projectId)
        {
            var result = Application.GetAllIdeasFromProject(new ProjectDto { Key = (ShortGuid)projectId });

            var ideasViewModel = new IdeaViewModel()
            {
                Ideas = Mapper.Map<IEnumerable<IdeaModel>>(result),
                ProjectId = projectId
            };

            return PartialView(ideasViewModel);
        }
    }
}

WareblocksWebUI/Views/Idea/Create.cshtml
@model WareblocksWebUI.Models.Idea.IdeaModel

<div class="row">
    @using (Html.BeginForm("Create", "Idea", FormMethod.Post, new { @class = "col s12" }))
    {
        @Html.AntiForgeryToken()
        <h4>Create a new idea</h4>
        <hr />
        @Html.ValidationSummary()

        <div class="row">
            <div class="input-field col s6">
                <i class="mdi-action-account-circle prefix"></i>
                @Html.TextBoxFor(m => m.Name, new { @class = "validate" })
                @Html.LabelFor(m => m.Name)
                @*<label for="icon_prefix">@Html.NameFor(m=>m.UserName)</label>*@
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <i class="mdi-action-perm-identity prefix"></i>
                @Html.TextBoxFor(m => m.Description, new { @class = "validate" })
                @Html.LabelFor(m => m.Description)
                @*<label for="icon_prefix">@Html.NameFor(m=>m.UserName)</label>*@
            </div>
        </div>
        @Html.HiddenFor(m => m.ProjectId)
        <div class="row">
            <div class="input-field col s6">
            </div>
            <div class="input-field col s6">
                <button class="btn waves-effect waves-light" type="submit" name="action">
                    Submit
                    <i class="mdi-content-send right"></i>
                </button>
            </div>
        </div>
    }
</div>

WareblocksWebUI/Views/Idea/IdeasByProject.cshtml
@model WareblocksWebUI.Models.Idea.IdeaViewModel

<div class="row">
    <div class="col s12 m4 l4">
        <div class="card">
            @Ajax.ActionLink(" ", "Create", "Idea", new { projectId = Model.ProjectId }, new AjaxOptions { HttpMethod = "GET", OnSuccess = "$('#modal').openModal()", UpdateTargetId = "modal" }, new { @class = "card-content add-background" })
        </div>
    </div>
    @foreach (var feature in Model.Ideas)
    {
        <div class="col s12 m4 l4">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="http://placehold.it/350x150">
                </div>
                <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4">@feature.Name <i class="mdi-navigation-more-vert right"></i></span>
                    <p><a href="@Url.Action("Index", "Feature" , new { featureId=feature.Key })">See more</a></p>
                </div>
                <div class="card-reveal">
                    <span class="card-title activator grey-text text-darken-4">@feature.Name <i class="mdi-navigation-more-vert right"></i></span>
                    <p>@feature.Description</p>
                </div>
            </div>
        </div>
    }
</div>

WareblocksWebUI/Views/Idea/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    @Html.Action("GetCommentsForIdea", "Comment", new { ideaId = Model.Key })
</div>